offensive_words = [
    "bandar ko chaak",
    "chapri",
    "bhalu",
    "chick dey",
    "chickne",
    "kera",
    "dhoti",
    "goo kha",
    "myatokni",
    "gula chus randi",
    "murdarr",
    "fucking ass",
    "fucking",
    "fuck",
    "jantha",
    "jatha",
    "jaatha",
    "jathaa",
    "lado",
    "fuck",
    "tero bau",
    "lado chus",
    "lado kha",
    "lado ko tuppo",
    "lang lang",
    "maa rondi!",
    "maa chikni",
    "machikne",
    "madhesi",
    "morr sali morr!",
    "muji",
    "prachanda",
    "puti chat chu",
    "puti chaat",
    "tutturay",
    "beshya",
    "bhalu ko poi",
    "chaak ko pwal",
    "chahk",
    "chahk ko dulka",
    "chak cha",
    "chaak",
    "chak",
    "condo",
    "condo handey",
    "dudh",
    "fushi kha",
    "gand faat cha",
    "goo kha",
    "goo khai-ra morr",
    "gula kha",
    "kukur chikni",
    "laando kha",
    "lado",
    "lado cocha",
    "lamto",
    "randi",
    "machikne",
    "gulla",
    "chikne"
    "ma shaala",
    "maa chikney!",
    "mandale",
    "maobadi",
    "mero fushi kha",
    "moot",
    "mootday",
    "moreko",
    "moreko manchi",
    "morryo",
    "murda",
    "maryo",
    "muji",
    "guu",
    "muzy",
    "mugi",
    "randi ko choro",
    "fuck",
    "puti kha",
    "randiko choro",
    "sungghur",
    "turi tauke",
    "myachikne",
    "machikne",
    "mya chikne",
    "ma chikne"
]